import { initializeApp, getApps } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged, User } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Safely attempt to load firebase config if generated by set_up_firebase
let firebaseConfig: any = null;
let isFirebaseConfigured = false;

try {
  // @ts-ignore
  firebaseConfig = require('../firebase-applet-config.json');
  isFirebaseConfigured = true;
} catch (e) {
  // Fallback or empty config if not yet provisioned via set_up_firebase
  firebaseConfig = {
    apiKey: "demo-api-key",
    authDomain: "demo-project.firebaseapp.com",
    projectId: "demo-project",
    storageBucket: "demo-project.appspot.com",
    messagingSenderId: "123456789",
    appId: "1:123456789:web:abcdef"
  };
}

export const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];
export const auth = getAuth(app);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId || undefined);
export const googleProvider = new GoogleAuthProvider();

export { isFirebaseConfigured, signInWithPopup, signOut, onAuthStateChanged };
export type { User };
